export const REVIEWS = [
// {
//     id: "5",
//     name: "Name Surname",
//     position: "Position, Company name",
//     text: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//     image: "/people/p1.avif",
//     network_img: "/people/network/upwork.svg",
//     rating: 5,
// },
// {
//     id: "4",
//     name: "Name Surname",
//     position: "Position, Company name",
//     text: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     image: "/people/p2.avif",
//     network_img: "/people/network/fiverr.svg",
//     rating: 4,
// },
// {
//     id: "3",
//     name: "Name Surname",
//     position: "Position, Company name",
//     text: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//     image: "/people/p3.avif",
//     network_img: "/people/network/linkedin.svg",
//     rating: 5,
// },
// {
//     id: "2",
//     name: "Name Surname",
//     position: "Position, Company name",
//     text: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//     image: "/people/p4.avif",
//     network_img: "/people/network/telegram.svg",
//     rating: 3,
// },
// {
//     id: "1",
//     name: "Name Surname",
//     position: "Position, Company name",
//     text: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//     image: "/people/p5.avif",
//     network_img: "/people/network/upwork.svg",
//     rating: 5,
// },
]